import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SocialSidebar } from "@/components/social/navbar/SocialSidebar";
import { is } from "date-fns/locale";
import { SocialBottomNav } from "@/components/social/navbar/SocialBottomNav";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
// //////////////////////////////////////////////////
// //////////////////////////////////////////////////
const isAuthenticated = true; // Replace with your authentication logic
// //////////////////////////////////////////////////
// //////////////////////////////////////////////////


  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      {/* <Sidebar /> */}
      <div className="flex ">
        <div className="z-100">

        {isAuthenticated && (
          <SocialSidebar />
        )}
        </div>
      {/* <div className="lg:pl-20 xl:pl-64"> */}
        {/* <TopBarSocial/> */}
        {/* <Navbar /> */}

        <main className="pb-20 lg:pb-0 w-full relative">{children}</main>
        {
          isAuthenticated && (
            <div>
              <SocialBottomNav />
            </div>
          )
        }
      </div>

      </body> 
    </html>
  );
}
